name: Library Lint

on:
  push:
  pull_request:
  schedule:
    - cron: "0 3 * * 6"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: arduino/arduino-lint-action@v1
        with:
          library-manager: update
          compliance: strict
